# DUPLIQUE ESTE ARQUIVO COMO ".streamlit/secrets.toml" NO STREAMLIT CLOUD (Settings > Secrets)

# Coletor ETH (failover por vírgula)
ETH_RPC_URL="https://ethereum.publicnode.com,https://eth.llamarpc.com,https://cloudflare-eth.com"

# JANELA DE LEITURA E LIMITES
ETH_BLOCKS_BACK="20"
ETH_MAX_TX="100"
ETH_INCLUDE_ETH_VALUE_MIN="0.01"

# Watchlist adicional por env (além do CSV)
ETH_MONITOR_ADDRESSES="0x28c6c06298d514db089934071355e5743bf21d60,0x7a250d5630b4cf539739df2c5dacb4c659f2488d"

# Engine
SCORE_ALERT_THRESHOLD="50"
AMOUNT_THRESHOLD="10000"
VELOCITY_WINDOW_MIN="10"
VELOCITY_MAX_TX="5"

# Dashboard
DASHBOARD_DEFAULT_CHAIN="ETH"

# Telegram (opcional)
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""
